### ISSUE TITLE
Break bedrock

### ISSUE THREAD

**Issue by SuperIsakSwahn** [xogeny/impact#112]
I am trying to play a terminator challenge (From Dreams minecraft) but the plugin for the terminator has so many issues that it literally puts you on top of bedrock somehow, and i got another plugin that allows you to break bedrock, but baritone doesn't try to break it at all. So how do i make it start breaking the bedrock?

**Comment by scorbett123** [comment]
Just so that the owners / maintainers of this repo know, this was meant for [here](https://github.com/ImpactDevelopment/ImpactIssues) according to [this message](https://github.com/cabaletta/baritone/issues/3078#issuecomment-967460496). It shouldn't have been created in that place originally, and definitely not meant for here.

Sorry for this.

**Comment by SuperIsakSwahn** [comment]
why did i expect anyone to have a clue what i meant...
