### ISSUE TITLE
Only look for top-level version annotations for library dependencies

### ISSUE THREAD

**Issue by dietmarw** [xogeny/impact#48]
A couple of libraries (e.g., Modelica_StateGraph2), throw currently an ugly Python error because *impact* finds several dependencies and self-dependencies. Now rather than exiting we should probably simply report those illegal nested "uses" annotations and only use the top-level one.

**Comment by xogeny** [comment]
Current `impact` handles self dependencies cleanly.  If you turn on the `-v` flag (*e.g.,* when installing) it also warns about invalid dependencies.  Not sure if that is sufficient.  Feel free to reopen, but this definitely shouldn't be part of the `v0.7.0` milestone in any case (since that is related to indexing)
