### ISSUE TITLE
"impact search" should return the result sorted

### ISSUE THREAD

**Issue by dietmarw** [xogeny/impact#80]
Also allow a list of ALL available libs. This seems currently to work with `impact search ""` but is not intuitive.

**Comment by xogeny** [comment]
This needs to be revisited with the Go version.

One thing to consider, when talking about searching.  When crawling, I just store all the libraries I crawl.  I do not store them by name (alone).  The point here is that there may be forks and I'd like to store all possible versions and then disambiguate which specific fork using some kind of URI as the true unique identifier.

Now, I haven't implemented this yet.  But if impacts `install` and `search` (and probably others) because of the need to handle the case where there are multiple versions of a library with the same name.  I'm not sure yet how to actually render that for end users.  But it is something we need to think about.

**Comment by xogeny** [comment]
One other comment...I propose sorting these by stars (with perhaps some kind of tweak to bump up official MA libraries).

**Comment by xogeny** [comment]
Was closed by a commit, but shouldn't have been.

**Comment by xogeny** [comment]
My plan is to provide a `--all` flag for search.  Normally, the default is "false" (i.e., don't display all possible results).  In that case, the search will only be done over the set of libraries that would be installed (i.e., the first with that name in the list unless explicitly called out by a `choice` settings in the users `impactrc` file).

In the case where the `--all` flag is set, the search results will show all libraries.  In the case where multiple libraries with the same name match, the one that would be installed will be shown as the "main" result and then all other matches will be shown as "also" matches.  The "also" matches will be sorted by rating (and the rating of the "main" result will indicate rating as well).

Sorting by rating only would be misleading because the user might assume that if they do an install, the highest rated one is the one that would get installed (since it would appear first in the list).  Showing them by order is also not good because a highly rated library might appear last.  So this is the best compromise I could think of where the selected library appears first and the remaining ones are sorted by rating.
